baseURL = 'blog.cloudham.com'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "nightfall"
[markup]
   [markup.tableOfContents]
      endLevel = 3
      ordered = false
      startLevel = 1 
