languageCode = 'en-us'

[menu]
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "blog"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"

[params]
author = "Cloud_Ham"
user = "Cloudham"
hostname = "https://github.com/Cloud-Ham/cloud-ham.github.io"

readingTime = false  # Show reading time on post page
published = true  # Show published data on post page

[[params.social]]
key = 0
name = "github"
url = "https://github.com/Cloud-Ham"

[[params.social]]
key = 1
name = "twitter"
url = "https://twitter.com/cloud_ham"

[[params.social]]
key = 2
name = "email"
url = "mailto:CloudHam001@gmail.com"
